apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
spec:
  rules:
  - http:
      paths:
      - path: /foothings
        backend:
          serviceName: hello-python-service
          servicePort: 6000